// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX_UEOsahx6sW1yPpefc4MRnauZac9fec',
    appId: '1:332810769234:web:b6f07c3cac13b9ce49a08b',
    messagingSenderId: '332810769234',
    projectId: 'travel-app-f1138',
    authDomain: 'travel-app-f1138.firebaseapp.com',
    storageBucket: 'travel-app-f1138.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkMsBFVISi8hDOfdMhzVQZo6tFV7r451k',
    appId: '1:332810769234:android:6da1fb5f664985a649a08b',
    messagingSenderId: '332810769234',
    projectId: 'travel-app-f1138',
    storageBucket: 'travel-app-f1138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARc6uZZAMraY2g_yAHxYbJOAfpq-_fyZY',
    appId: '1:332810769234:ios:fb67445d3b6e7eb149a08b',
    messagingSenderId: '332810769234',
    projectId: 'travel-app-f1138',
    storageBucket: 'travel-app-f1138.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARc6uZZAMraY2g_yAHxYbJOAfpq-_fyZY',
    appId: '1:332810769234:ios:fb67445d3b6e7eb149a08b',
    messagingSenderId: '332810769234',
    projectId: 'travel-app-f1138',
    storageBucket: 'travel-app-f1138.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX_UEOsahx6sW1yPpefc4MRnauZac9fec',
    appId: '1:332810769234:web:4baf3f8a6199e10849a08b',
    messagingSenderId: '332810769234',
    projectId: 'travel-app-f1138',
    authDomain: 'travel-app-f1138.firebaseapp.com',
    storageBucket: 'travel-app-f1138.firebasestorage.app',
  );
}
